### ISSUE TITLE
how does tensorRT monodepth precision

### ISSUE THREAD

**Issue by FangJingYunner** [mehmetkinaci/TensorRT-Monodepth2#1]
hello, l want to export onnx of monodepth2 and deployment it with tensorRT on embed system. 
when
but when l use onnx runtime to infer the result is very bad.How  do you transfer pth into trt engine?

**Comment by mehmetkinaci** [comment]
In this project, I create weights files with .wts extension from pth file. TRT engine uses this model by serializing it. You can find the script to create a WTS file at https://github.com/wang-xinyu/tensorrtx
